### ISSUE TITLE
errors?

### ISSUE THREAD

**Issue by Cutcorwn** [ByMykel/CSGO-API#133]
![image](https://github.com/user-attachments/assets/2b1ccad2-15e7-4c08-bf26-8cee75de56b0)
![image](https://github.com/user-attachments/assets/5834d01a-d70c-4c36-a6b3-b36f9f7ec555)

The new major items have some errors that the previous major ones do not have
The souvenir packages and the viewer pass are returning only null
Another issue is that the images of the souvenirs are not working

**Comment by Cutcorwn** [comment]
It is returning only null for all souvenir packages and the images are not working. In the "viewer pass", it is missing rarity

**Comment by ByMykel** [comment]
The images were not working because they were in a folder that i was not tracking and the rarity is null because a function was not up to date.

The images are already working but the rarity will be fixed in the next update.

**Comment by Ou7law007** [comment]
> The images were not working because they were in a folder that i was not tracking and the rarity is null because a function was not up to date.
> 
> The images are already working but the rarity will be fixed in the next update.

I don't want to hijack this issue, but is there a way that you can add `item_nameid`s? Or is there an easy way to get them for any given skin?

**Comment by ByMykel** [comment]
> > The images were not working because they were in a folder that i was not tracking and the rarity is null because a function was not up to date.
> > The images are already working but the rarity will be fixed in the next update.
> 
> I don't want to hijack this issue, but is there a way that you can add `item_nameid`s? Or is there an easy way to get them for any given skin?

You adding the `item_name`? If you can explain how is that attribute useful I can add it without problem.

![image](https://github.com/user-attachments/assets/7435a616-4442-48e7-9640-eb42491d7d02)

**Comment by NallaEXE** [comment]
hello, advantage of the topic about images, you want to know how websites get skin images in the "flat" format, like this?

![image](https://github.com/user-attachments/assets/577909ee-7fa8-4b17-af39-1b197f1871dc)
![image](https://github.com/user-attachments/assets/9f476565-6e39-4882-b761-25e4d01cb9bd)

I’ve been searching through the game files and haven’t found anything related to it. I’d like to know how they manage to get these images, since some sites use canvas, but I don’t understand how they take the skin model and convert it into a 2D flat format
