### ISSUE TITLE
Can we add that to the name of the weapon

### ISSUE THREAD

**Issue by hackeryutu** [ByMykel/CSGO-API#21]
"SFUI_InvTooltip_Wear_Amount_0"						"Factory New"
"SFUI_InvTooltip_Wear_Amount_1"						"Minimal Wear"
"SFUI_InvTooltip_Wear_Amount_2"						"Field-Tested"
"SFUI_InvTooltip_Wear_Amount_3"						"Well-Worn"
"SFUI_InvTooltip_Wear_Amount_4"						"Battle-Scarred"

P2000 | Amber Fade (${SFUI_InvTooltip_Wear_Amount_?})
P2000 | Chainmail (${SFUI_InvTooltip_Wear_Amount_?})
P250 | Bengal Tiger (${SFUI_InvTooltip_Wear_Amount_?})
P250 | Bone Mask (${SFUI_InvTooltip_Wear_Amount_?})

**Comment by ByMykel** [comment]
With the current structure I will not add the wear to the name because a lot of data would be repeated. I can add a property
named `wears` with all the wears.
```json
{
    "id": "skin-65604",
    "name": "Desert Eagle | Urban DDPAT",
    "description": "As expensive as it is powerfu...",
    "weapon": "Desert Eagle",
    "pattern": "Urban DDPAT",
    "min_float": 0.06,
    "max_float": 0.8,
    "rarity": "Consumer Grade",
    "stattrak": false,
    "image": "https://steamcdn-a.akamaihd.n..."

    "wears": ["Factory New", "Minimal Wear", "..."]
}
```

**Comment by hackeryutu** [comment]
Okay

**Comment by ByMykel** [comment]
@hackeryutu You can propose me a better structure if you think is better for the general use of this API.

**Comment by hackeryutu** [comment]
@ByMykel I think your data structure is very good

**Comment by ErezShahaf** [comment]
> With the current structure I will not add the wear to the name because a lot of data would be repeated. I can add a property named `wears` with all the wears.
> 
> ```json
> {
>     "id": "skin-65604",
>     "name": "Desert Eagle | Urban DDPAT",
>     "description": "As expensive as it is powerfu...",
>     "weapon": "Desert Eagle",
>     "pattern": "Urban DDPAT",
>     "min_float": 0.06,
>     "max_float": 0.8,
>     "rarity": "Consumer Grade",
>     "stattrak": false,
>     "image": "https://steamcdn-a.akamaihd.n..."
> 
>     "wears": ["Factory New", "Minimal Wear", "..."]
> }
> ```

I actually think that creating a different object for each wear would make the API way more useful even if it seems like the data is repetitive since each wear has it's own min_float, max_float, steam url, and so on. Some websites need those values, for example - if you log into buff163 and look for a specific weapon in a specific wear you would be able to sort see the min and max values of that specific wear.

An alternative way to do that would be to add a nested object which has all the wears and their min-max float values.

Would be pretty useful for many developers, although items_game.txt doesn't seem to contain that data so it would have to be scraped from somewhere else.

**Comment by ByMykel** [comment]
@ErezShahaf If I'm not mistaken the min and max float values for every wear are the same:

![image](https://github.com/ByMykel/CSGO-API/assets/38622893/3943f756-ef6c-4303-8c85-4272b601833d)
### 


But one thing I did't notice before, that the images are not the same for all wears:
![image](https://github.com/ByMykel/CSGO-API/assets/38622893/756cb1fd-2022-44b2-af38-2073069b2e1b)
![image](https://github.com/ByMykel/CSGO-API/assets/38622893/76fc421e-136d-4653-aba1-56ade91799c7)

I could do something with nested objects to display the different images for every wear but I can't find all the images.

For example for 'AWP | Corticera' I have 3 different images, but for the most of the skins I only have one.
```
    "econ/default_generated/weapon_awp_cu_favela_awp_heavy_large": "https://steamcdn-a.akamaihd.net/apps/730/icons/econ/default_generated/weapon_awp_cu_favela_awp_heavy_large.e7e7ee23215e0ccfb22d39500522a0e4128500fa.png",
    "econ/default_generated/weapon_awp_cu_favela_awp_light_large": "https://steamcdn-a.akamaihd.net/apps/730/icons/econ/default_generated/weapon_awp_cu_favela_awp_light_large.4329c047ea1899f3846a1a81539ba2a27665a54e.png",
    "econ/default_generated/weapon_awp_cu_favela_awp_medium_large": "https://steamcdn-a.akamaihd.net/apps/730/icons/econ/default_generated/weapon_awp_cu_favela_awp_medium_large.7578b4d3233ca9d1e47cf51e6fd26fb38048a5ba.png",
```

**Comment by ByMykel** [comment]
@hackeryutu Until we find a better structure for the skins I think you can calculate the wears yourself using this image:

![image](https://github.com/ByMykel/CSGO-API/assets/38622893/9677c1f5-bd14-4124-bb7f-ec0ccc937ab1)

**Comment by ErezShahaf** [comment]
> @ErezShahaf If I'm not mistaken the min and max float values for every wear are the same:
> 
> ![image](https://user-images.githubusercontent.com/38622893/238739312-3943f756-ef6c-4303-8c85-4272b601833d.png)
> 
> But one thing I did't notice before, that the images are not the same for all wears: ![image](https://user-images.githubusercontent.com/38622893/238748235-756cb1fd-2022-44b2-af38-2073069b2e1b.png) ![image](https://user-images.githubusercontent.com/38622893/238748375-76fc421e-136d-4653-aba1-56ade91799c7.png)
> 
> I could do something with nested objects to display the different images for every wear but I can't find all the images.
> 
> For example for 'AWP | Corticera' I have 3 different images, but for the most of the skins I only have one.
> 
> ```
>     "econ/default_generated/weapon_awp_cu_favela_awp_heavy_large": "https://steamcdn-a.akamaihd.net/apps/730/icons/econ/default_generated/weapon_awp_cu_favela_awp_heavy_large.e7e7ee23215e0ccfb22d39500522a0e4128500fa.png",
>     "econ/default_generated/weapon_awp_cu_favela_awp_light_large": "https://steamcdn-a.akamaihd.net/apps/730/icons/econ/default_generated/weapon_awp_cu_favela_awp_light_large.4329c047ea1899f3846a1a81539ba2a27665a54e.png",
>     "econ/default_generated/weapon_awp_cu_favela_awp_medium_large": "https://steamcdn-a.akamaihd.net/apps/730/icons/econ/default_generated/weapon_awp_cu_favela_awp_medium_large.7578b4d3233ca9d1e47cf51e6fd26fb38048a5ba.png",
> ```

That would have made things easier, unfortunately each weapon has different ranges for their wear names. For example, one factory new could be between 0 to 0.06 and for the other weapon it could be from 0.2 to 0.1.

Would you have noticed in your image is the spray pattern, which also complicates things if you wanted to do it perfectly. For the floats you could just scrape them from somewhere else but if you wanted the accurate image it requires a server and SteamUser package in order to send a request to the game coordinator. Another thing that you could do is scrape each image pattern if you wanted it to be more or less accurate.

It's up to you if you want to do something about it, I just wanted to let you know that those differences exist. I think that the floats are by far more important.

**Comment by ByMykel** [comment]
>That would have made things easier, unfortunately each weapon has different ranges for their wear names. For example, one factory new could be between 0 to 0.06 and for the other weapon it could be from 0.02 to 0.1.

Could you give one example?

I definitely want to add nested objects so I can add extra things like market hash name, accurate images for every wear, float values, etc. But I think that woud be some kind of hard to do without scraping some site.

**Comment by ByMykel** [comment]
@hackeryutu Deployed. Sorry for the delay I should have added this before.
